### ISSUE TITLE
Corrupt EMWIN images on Windows

### ISSUE THREAD

**Issue by JVital2013** [altillimity/SatDump#190]
**Description of the issue**

When Receiving the HRIT signal from GOES-16 with SatDump on Windows, the EMWIN images are corrupt. All other data is fine, and there are no errors in the log (including no CRC errors). The issue is not present when running SatDump on Linux with the same hardware.

**Hardware (SDR/PC/OS)**

SDR: NooElec NESDR SmarTee XTR
OS: Windows 10 Build 21H2
CPU: Intel(R) Core(TM) i5-6600K CPU
Memory: 16GB RAM
GPU: AMD Radeon RX 580
Visual Studio 2015-2022 Redistributable version: 14.34.31931.0

**Version (Eg, 1.0.0, CI Build #171)**

Every build I tested, 1.0 through Windows CI Build #729

**Logs after the crash (satdump.logs)**

N/A

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**

A bunch of examples of corrupt files: [EMWIN.zip](https://github.com/altillimity/SatDump/files/10052692/EMWIN.zip). I have these same files "uncorrupt" as received by goesproc, if that's helpful - it will just take a bit to dig them out.

Most of the images are completely corrupt, but some of them look ok for the first few blocks:
![Z_EIPU00KWBC190145_C_KWIN_20221119134523_060434-4-IMGSJUPR](https://user-images.githubusercontent.com/24253715/202955858-ec50bc75-2ed5-4434-ae08-62dda2604f72.JPG)

**Comment by Aang23** [comment]
Hello! Well, this has actually already been fixed, after 1.0.0 and build #729.

**Comment by Aang23** [comment]
Ah wait, I misread the build number.

Do you have a CADU file I could test with on hand? I know this is fixed on Linux, but perhaps I did miss something.

**Comment by Aang23** [comment]
Well, found one. Will debug shortly.

**Comment by JVital2013** [comment]
Sounds good - I can ship one over in a few hours too. I believe I still have the cadu file from the images in the attached zip

**Comment by JVital2013** [comment]
Sorry, it looks like the SatDump live processing no longer outputs a cadu file automatically for me anymore. Can you point me in the right direction on how to get that?

**Comment by Aang23** [comment]
You need to edit the GOES.json file in pipelines. In goes_hrit, change

```
 "default": [
                [
                    1,
                    0
                ],
                [
                    2,
                    0
                ],
                [
                    3,
                    0
                ]
            ],
```
to
```
 "default": [
                [
                    1,
                    0
                ],
                [
                    2,
                    0
                ]
            ],
```

**Comment by Aang23** [comment]
As a note, I've just ran a CADU on my (Linux) machine. 
![20221114230045-GULF_latest lrit](https://user-images.githubusercontent.com/23421917/203127771-43b3c800-1510-4138-b5e6-d800b9524893.gif)
![Z_QGTA98KWNS141015_C_KWIN_20221114221525_825437-4-IMGWWAUS](https://user-images.githubusercontent.com/23421917/203127802-24620ec8-4f95-4fc0-9be8-2c3e9324fc98.PNG)

All images are fine. Time to test on Windows.

**Comment by Aang23** [comment]
Fixed, this was an usual Windows issue (differentiating text & binary writing when it's the same on Linux)

**Comment by JVital2013** [comment]
Thanks - unfortunately, SatDump just crashes now as soon as I start the GOES HRIT pipeline. Log attached
[satdump.log](https://github.com/altillimity/SatDump/files/10059866/satdump.log)

**Comment by Aang23** [comment]
@JVital2013 fixed.

**Comment by JVital2013** [comment]
@Aang23 indeed it is! I can confirm that EMWIN imagery now saves fine on Windows, and there are no more crashes with live processing.

Thanks for your hard work on this. SatDump is rapidly maturing into a highly-functional piece of code!

**Comment by Aang23** [comment]
Awesome.

You're welcome! Thanks. Will be getting to your other issues soon by the way.
