### ISSUE TITLE
Himawaricast - stol argument out of range

### ISSUE THREAD

**Issue by eswnl** [altillimity/SatDump#192]
**Description of the issue**
When trying to process himawaricast transport stream

**Hardware (SDR/PC/OS)**
TBS5927

**Version (Eg, 1.0.0, CI Build #171)**

**Logs after the cras (satdump.logs)**
[11/22/22 - 13:30:53] (I) Using input frames E:\DVB_stream\0.0E_4148.146_H_2586_(2021-05-03 02.58.45)_dump.ts
[11/22/22 - 13:30:53] (I) Decoding to C:\Users\john\Desktop\HimawariTest
[11/22/22 - 13:30:53] (I) New xRIT file : IMG_DK01B11_202105021750_004
[11/22/22 - 13:30:53] (D) This is image data. Size 2750x275
[11/22/22 - 13:30:53] (E) Fatal error running pipeline : stol argument out of range
[11/22/22 - 13:31:12] (I) Saving user config at settings.json
[11/22/22 - 13:31:12] (I) UI Exit
[11/22/22 - 13:31:12] (I) Exiting!

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![image](https://user-images.githubusercontent.com/59115800/203222796-4fcf8f00-04bb-4828-af69-98ae351c21cd.png)

**Comment by Aang23** [comment]
I can't reproduce the issue with the data I have... Do you have further samples I could utilize to try and reproduce?

**Comment by eswnl** [comment]
Just sent the file.

**Comment by Aang23** [comment]
Should be fixed!

**Comment by eswnl** [comment]
I just downloaded newest build and still get the same error message.

**Comment by Aang23** [comment]
Well, interesting. I guess I'll check on Windows.

**Comment by Aang23** [comment]
Should be good now.

**Comment by eswnl** [comment]
Hmm.
![image](https://user-images.githubusercontent.com/59115800/204144899-1a8a37da-5ada-4c8d-82db-444b8cdedbb6.png)

**Comment by Aang23** [comment]
Hm... So it looks there's a separate issue entirely on Windows. Let me see...

**Comment by Aang23** [comment]
Ok, figured it out... Another weird windows thing.

**Comment by eswnl** [comment]
Working now. I got the "empty png" message. It also says there is 11000x11000 file but it did not output the image for it.
![image](https://user-images.githubusercontent.com/59115800/204242525-a91bb88f-1ad3-4822-9767-739e59070d30.png)
I'll keep playing.
